clear functions;

scriptDir = fileparts(mfilename('fullpath'));
root = fileparts(scriptDir);
oldDir = pwd;
cleanupObj = onCleanup(@() cd(oldDir));

src = fullfile(root, 'src');
outDir = fullfile(root, 'mex', 'win64_msvc_ifx_mumps_ma57_solver_static');
if ~exist(outDir, 'dir'), mkdir(outDir); end

ipopt = fullfile(root, 'install', 'ipopt_msvc_ifx_mumps_ma57');
mumps = getenvRequired('MUMPS_ROOT');
mkl = getenvDefault('MKL_ROOT', 'C:/Program Files (x86)/Intel/oneAPI/mkl/latest');
intelCompiler = getenvDefault('INTEL_COMPILER_ROOT', 'C:/Program Files (x86)/Intel/oneAPI/compiler/latest');
ipoptSrc = getenvRequired('IPOPT_SRC');
hsl = fullfile(root, 'install', 'hsl_stubs', 'lib', 'ipopt_mex_hsl_link_stubs.lib');

libs = { ...
  fullfile(ipopt, 'lib', 'ipopt.lib'), ...
  hsl, ...
  fullfile(mumps, 'lib', 'libdmumps.lib'), ...
  fullfile(mumps, 'lib', 'libmumps_common.lib'), ...
  fullfile(mumps, 'lib', 'libpord.lib'), ...
  fullfile(mumps, 'lib', 'libmpiseq.lib'), ...
  fullfile(mkl, 'lib', 'mkl_intel_lp64.lib'), ...
  fullfile(mkl, 'lib', 'mkl_sequential.lib'), ...
  fullfile(mkl, 'lib', 'mkl_core.lib'), ...
  fullfile(intelCompiler, 'lib', 'libircmt.lib'), ...
  fullfile(intelCompiler, 'lib', 'libifcoremt.lib'), ...
  fullfile(intelCompiler, 'lib', 'libifport.lib'), ...
  fullfile(intelCompiler, 'lib', 'libmmt.lib'), ...
  fullfile(intelCompiler, 'lib', 'svml_dispmt.lib') ...
};

requiredFiles = [ ...
  {fullfile(src, 'ipopt_setfunctions.cc'), ...
   fullfile(src, 'IpoptInterfaceCommon_safe.cc'), ...
   fullfile(src, 'IpoptInterfaceCommon.hh'), ...
   fullfile(src, 'matlab_ma57_setfunctions_bridge.cpp'), ...
   fullfile(src, 'ma28_dependency_detector_unavailable.cpp'), ...
   fullfile(ipopt, 'include', 'coin-or', 'IpoptConfig.h')}, ...
  libs ...
];

for k = 1:numel(requiredFiles)
  if ~isfile(requiredFiles{k})
    error('Missing required file: %s', requiredFiles{k});
  end
end

cd(root);

args = {'-v', '-largeArrayDims', ...
  ['-I', src], ...
  ['-I', fullfile(ipopt, 'include', 'coin-or')], ...
  ['-I', fullfile(mumps, 'include')], ...
  ['-I', fullfile(mumps, 'libseq')], ...
  ['-I', fullfile(ipoptSrc, 'src', 'Algorithm', 'LinearSolvers')], ...
  '-DOS_WIN', ...
  '-DMATLAB_MEX_FILE', ...
  '-DNOMINMAX', ...
  '-output', fullfile(outDir, 'ipopt'), ...
  fullfile(src, 'ipopt_setfunctions.cc'), ...
  fullfile(src, 'IpoptInterfaceCommon_safe.cc'), ...
  fullfile(src, 'matlab_ma57_setfunctions_bridge.cpp'), ...
  fullfile(src, 'ma28_dependency_detector_unavailable.cpp'), ...
  'COMPFLAGS=$COMPFLAGS /EHsc /O2 /MD', ...
  ['LINKFLAGS=$LINKFLAGS /NODEFAULTLIB:libmmd.lib /NODEFAULTLIB:libcmt.lib /LIBPATH:"', fullfile(mkl, 'lib'), '" /LIBPATH:"', fullfile(intelCompiler, 'lib'), '"'], ...
  libs{:}};

mex(args{:});
fprintf('Built solver-static IPOPT MEX: %s\n', fullfile(outDir, ['ipopt.', mexext]));

function value = getenvRequired(name)
value = getenv(name);
if isempty(value)
  error('Required environment variable %s is not set.', name);
end
end

function value = getenvDefault(name, defaultValue)
value = getenv(name);
if isempty(value)
  value = defaultValue;
end
end
