clear functions;
oldDir = pwd;
cleanupObj = onCleanup(@() cd(oldDir));

root = getenv_or_default('IPOPT_R7_SANDBOX_ROOT', fileparts(fileparts(mfilename('fullpath'))));
toolbox = getenv('IPOPT_MEX_TOOLBOX');
if isempty(toolbox)
    error('Set IPOPT_MEX_TOOLBOX to the mexIPOPT/toolbox directory.');
end

tmpRoot = getenv_or_default('TMP_ROOT', '/tmp/ipopt-r7-linux-ma57-sandbox');
cc = getenv_or_default('CC', '/usr/bin/x86_64-linux-gnu-gcc-12');
cxx = getenv_or_default('CXX', '/usr/bin/g++-12');
ld = getenv_or_default('LD', cxx);

ipoptPrefix = getenv_or_default('IPOPT_PREFIX', ...
    fullfile(tmpRoot, 'install-linux', 'ipopt_loader'));
ipoptSourceTree = getenv_or_default('IPOPT_SOURCE_TREE', ...
    fullfile(root, 'third_party', 'src', 'Ipopt-releases-3.14.19'));
mumpsPrefix = getenv_or_default('MUMPS_PREFIX', ...
    fullfile(tmpRoot, 'install-linux', 'mumps'));
metisPrefix = getenv_or_default('METIS_PREFIX', ...
    fullfile(tmpRoot, 'install-linux', 'metis'));
gklibPrefix = getenv_or_default('GKLIB_PREFIX', ...
    fullfile(tmpRoot, 'install-linux', 'gklib'));
openblasPrefix = getenv_or_default('OPENBLAS_PREFIX', ...
    fullfile(tmpRoot, 'install-linux', 'openblas'));

bridgeSrc = fullfile(root, 'src', 'ma57_bridge_source', 'matlab_ma57_setfunctions_bridge_linux.cpp');

libipopt = fullfile(ipoptPrefix, 'lib', 'libipopt.a');
libmumps = fullfile(mumpsPrefix, 'lib', 'libcoinmumps.a');
libmetis = fullfile(metisPrefix, 'lib', 'libmetis.a');
libgklib = fullfile(gklibPrefix, 'lib', 'libGKlib.a');
libopenblas = fullfile(openblasPrefix, 'lib', 'libopenblas.a');

requiredFiles = {libipopt, libmumps, libmetis, libgklib, libopenblas, bridgeSrc};
assert_files_exist(requiredFiles);
assert_files_exist({cc, cxx, ld});
assert_files_exist({fullfile(ipoptSourceTree, 'src', 'Algorithm', 'LinearSolvers', 'IpMa57TSolverInterface.hpp')});

outDir = fullfile(root, 'bin', 'mexa64');
if ~exist(outDir, 'dir'), mkdir(outDir); end

cd(toolbox);

libs = strjoin({ ...
    '-Wl,--start-group', ...
    q(libipopt), q(libmumps), q(libmetis), q(libgklib), q(libopenblas), ...
    '-Wl,--end-group', ...
    '-lstdc++', '-lgfortran', '-lquadmath', '-ldl', '-lm', '-lpthread' ...
}, ' ');

exportedSymbols = strjoin({ ...
    '-Wl,--export-dynamic-symbol=ma57ad', ...
    '-Wl,--export-dynamic-symbol=ma57bd', ...
    '-Wl,--export-dynamic-symbol=ma57cd', ...
    '-Wl,--export-dynamic-symbol=ma57ed', ...
    '-Wl,--export-dynamic-symbol=ma57id', ...
    '-Wl,--export-dynamic-symbol=ma57ad_', ...
    '-Wl,--export-dynamic-symbol=ma57bd_', ...
    '-Wl,--export-dynamic-symbol=ma57cd_', ...
    '-Wl,--export-dynamic-symbol=ma57ed_', ...
    '-Wl,--export-dynamic-symbol=ma57id_' ...
}, ' ');

args = { ...
    '-v', ...
    '-largeArrayDims', ...
    ['-I', fullfile(root, 'src', 'mex')], ...
    ['-I', fullfile(ipoptPrefix, 'include', 'coin-or')], ...
    ['-I', fullfile(ipoptSourceTree, 'src', 'Algorithm', 'LinearSolvers')], ...
    '-output', fullfile(outDir, 'ipopt'), ...
    fullfile(root, 'src', 'mex', 'ipopt.cc'), ...
    fullfile(root, 'src', 'mex', 'IpoptInterfaceCommon.cc'), ...
    bridgeSrc, ...
    ['CC=', cc], ...
    ['CXX=', cxx], ...
    ['LD=', ld], ...
    ['LINKLIBS=$LINKLIBS ', libs], ...
    ['LDFLAGS=$LDFLAGS ', exportedSymbols], ...
    'CFLAGS=$CFLAGS -O2 -fPIC -fno-lto', ...
    'CXXFLAGS=$CXXFLAGS -Wall -O2 -fPIC -std=gnu++17 -fno-lto' ...
};

mex(args{:});

fid = fopen(fullfile(outDir, 'ma57_embedded_bridge.txt'), 'w');
if fid < 0
    error('Could not write bridge marker file.');
end
cleanupFid = onCleanup(@() fclose(fid));
fprintf(fid, 'embedded_ma57_bridge=yes\n');
fprintf(fid, 'matlab_ma57=runtime_loaded\n');
fprintf(fid, 'supported_linear_solvers=mumps,ma57\n');
fprintf(fid, 'invalid_linear_solver_status=-999\n');

fprintf('Built Linux IPOPT MEX: %s\n', fullfile(outDir, ['ipopt.', mexext]));

function s = q(p)
    s = ['"', strrep(p, '\', '/'), '"'];
end

function value = getenv_or_default(name, fallback)
    value = getenv(name);
    if isempty(value)
        value = fallback;
    end
end

function assert_files_exist(files)
    for k = 1:numel(files)
        if ~isfile(files{k})
            error('Missing required file: %s', files{k});
        end
    end
end
